---
- name: "manageiq-vmdb role for inserting new vm name into the state machine"
  hosts: localhost
  connection: local
  vars:
  - manageiq_validate_certs: false
  
  roles:
  - manageiq-core.manageiq-vmdb

  tasks:   
  - name: Get a vmdb request
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
    register: service
    
  - name: Print the service details
    debug:
      msg: "Request task: {{ service }}"
      
  - name: "Update task with new VM Name information"
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
      action: edit
      data:
        options:
          vm_target_name: myvm002
    register: name
          
  - name: Print the result
    debug:
      msg: "The new VM name is {{ name }}"