---
- name: "manageiq-vmdb role for inserting new vm name into the state machine"
  hosts: localhost
  connection: local
  vars:
  - manageiq_validate_certs: false
  
  roles:
  - manageiq-core.manageiq-vmdb
  - manageiq-core.manageiq-automate

  tasks:   
  - name: "Get a vmdb request"
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
    register: vmrequest
          
  - name: "Print the vmdb request"
    #debug: msg="{{ vmrequest }}"
    debug: var=vmrequest.options.vm_target_name

  - name: "Set a State Var"
    manageiq_automate:
      workspace: "{{ workspace }}"
      set_state_var:
        attribute: "ansible_stats_vmname"
        value: vmrequest.options.vm_target_name
   
  - name: Check whether a "ansible_stats_vmname" state var exists (state_var_exists)
    manageiq_automate:
      workspace: "{{ workspace }}"
      state_var_exists:
        attribute: "ansible_stats_vmname"
      register: state_var_exists
    - debug: msg="Result:{{ state_var_exists.value }}"