---
- name: Insert a new IP into State machine using manageiq-vmdb
  hosts: all
  
  roles:
  - manageiq-core.manageiq-vmdb

  tasks:   
  - name: Update task with new IP information
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
      action: edit
      data:
        options:
          addr_mode: ["static", "Static"]
          ip_addr: "{{ ip_addr }}"
          subnet_mask: "{{ netmask | default(255.255.255.0) }}"
          gateway: "{{ gateway | default(192.168.0.2) }}"