---
- name: "manageiq-vmdb role for inserting network values into a state machine"
  hosts: localhost
  connection: local
  vars:
  - manageiq_validate_certs: false
  
  roles:
  - manageiq-core.manageiq-vmdb

  tasks:
  - name: Get a vmdb request
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
    register: service
    
  - name: "Update task with new IP information"
    manageiq_vmdb:
      href: "{{ manageiq.request_task }}"
      action: edit
      data:
        options:
          #addr_mode: ["static", "Static"]
          ip_addr: "{{ ip_addr }}"
          hostname: "{{ vm_target_hostname }}"
          #subnet_mask: "24"
          #gateway: "192.168.0.2"
    register: ipaddr

  - name: "Save hostname for later use in Playbooks"
    set_stats:
      data:
        hostname: "{{ hostname }}"
          