---
- name: get next free IP
  hosts: all
  vars:
    phpipam_user: admin
    phpipam_password: "r3dh4t1!"
    phpipam_url: "https://ipam.example.com/api"

  tasks:
  - name: log into phpIPAM
    uri:
      url: "{{ phpipam_url }}/ansible/user/"
      user: "{{ phpipam_user }}"
      password: "{{ phpipam_password }}"
      method: POST
      status_code: 200
      validate_certs: no
    register: login

  - name: get next free IP
    uri:
      url: "{{ phpipam_url }}/ansible/subnets/8/first_free/"
      headers:
        token: "{{ login.json.auth_token }}"
      status_code: 200
      validate_certs: no
    register: next_ip

  - name: print next IP
    debug:
      var: next_ip

