---
- name: This playbook will register the system on Satellite
  hosts: all
  vars:
  - satserver: "sat.example.com"
  - activationkey: "ak-Reg_To_Production"
  - organization: "Example_com"

  tasks:
  - name: Register with activation key
    redhat_subscription:
      state: present
      server_hostname: "{{ satserver }}"
      org_id: "{{ organization }}"
      activationkey: "{{ activationkey }}"
      server_insecure: disable
